-- ============================================================
-- Notas de repaso (Mi Estudio)
-- Ejecutar en Supabase -> SQL Editor.
--
-- Cada vez que la ruleta te saca algo y lo repasas, le pones una nota de 1 a 100.
-- La nota cambia la probabilidad de que eso vuelva a salir: lo que sacaste por
-- encima de 90 aparece la mitad de seguido, para que el sorteo insista en lo que
-- todavia no dominas en vez de repetirte lo que ya sabes.
--
-- Se guarda el historial completo, una fila por intento, y para el peso se usa la
-- nota mas reciente. Asi se puede ver si un tema mejora o empeora con el tiempo.
--
-- 'punto' es null cuando la nota es del subtema entero (los que todavia no tienen
-- puntos de repaso cargados con el boton de las tijeras).
-- ============================================================

create table if not exists notas_estudio (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tema       text not null,
  subtema    text not null,
  punto      text,
  nota       smallint not null check (nota between 1 and 100)
);

-- La consulta de siempre: la ultima nota de cada cosa.
create index if not exists notas_estudio_idx
  on notas_estudio (tema, subtema, created_at desc);

-- ------------------------------------------------------------
-- Permisos (RLS): como el resto de las tablas del proyecto, sin login.
-- ------------------------------------------------------------

alter table public.notas_estudio disable row level security;
