-- ============================================================
-- Lista de compras
-- Ejecutar en Supabase -> SQL Editor.
--
-- 'compras'  = lo que falta comprar, con el tipo de tienda donde se consigue.
-- 'lugares'  = tiendas guardadas con sus coordenadas; la app compara tu
--              posicion contra ellas para avisarte cuando estas en una.
-- ============================================================

create table if not exists compras (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nombre      text not null,                      -- 'leche entera'
  cantidad    text,                               -- '2 litros', '1 caja'
  categoria   text not null default 'supermercado', -- tienda principal (retro-compatible)
  categorias  text[] not null default array['supermercado']::text[], -- todas las tiendas donde se consigue
  nota        text,                               -- la frase dictada de la que salio
  comprado    boolean not null default false,
  comprado_at timestamptz
);

-- Un articulo suele conseguirse en mas de un lado: el pan brioche en la panaderia y
-- en el super, el pegamento instantaneo en la ferreteria y en el super. 'categorias'
-- guarda esa lista; 'categoria' queda como la principal, por compatibilidad con
-- filas viejas y con la version anterior de la app.
alter table public.compras add column if not exists categorias text[];
update public.compras set categorias = array[categoria]
  where categorias is null or cardinality(categorias) = 0;

create index if not exists compras_pendientes_idx
  on compras (comprado, categoria);

create table if not exists lugares (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nombre      text not null,                      -- 'Carrefour City Rue de Rennes'
  categoria   text not null default 'supermercado',
  lat         double precision not null,
  lon         double precision not null,
  radio       int not null default 120            -- metros: que tan cerca contas como "estoy ahi"
);

-- ------------------------------------------------------------
-- Permisos (RLS)
-- La app no tiene login: todo entra con la anon key, igual que el resto
-- de las tablas del proyecto. Una tabla creada por SQL ya viene sin RLS,
-- pero si la creaste desde el Table Editor si lo tiene, y sin politicas
-- el select devuelve [] en silencio y el insert falla con 42501.
-- Estas dos lineas dejan ambas tablas como las demas, y no molestan si
-- RLS ya estaba apagado.
-- ------------------------------------------------------------

alter table public.compras disable row level security;
alter table public.lugares disable row level security;
