-- ============================================================
-- Puntos de repaso para el sorteo de Mi Estudio
-- Ejecutar en Supabase -> SQL Editor.
--
-- Sirven para partir un subtema largo en trozos concretos sobre los
-- que autoevaluarse. NO tocan el plan: los subtemas y sus metas
-- siguen siendo los de siempre. Solo los usa el sorteo: cuando un
-- subtema pasa el 90% de su meta, el sorteo elige uno de sus puntos
-- (o el subtema entero si no tiene puntos cargados).
--
-- Sin esta tabla la app funciona igual, solo que no deja crear puntos.
-- ============================================================

create table if not exists puntos_repaso (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  tema        text not null,   -- 'Déontologie', 'Droit civil', ...
  subtema     text not null,   -- subtema del plan al que pertenece
  texto       text not null    -- el punto concreto a repasar
);

create index if not exists puntos_repaso_tema_subtema_idx
  on puntos_repaso (tema, subtema);

-- ------------------------------------------------------------
-- Permisos (RLS)
-- Si creaste la tabla desde el Table Editor del dashboard, Supabase
-- le activa RLS y sin politicas nadie puede leer ni escribir:
-- el select devuelve [] en silencio y el insert falla con 42501.
-- La app no tiene login (todo entra con la anon key), asi que se
-- deja igual que las demas tablas del proyecto: sin RLS.
-- ------------------------------------------------------------

alter table public.puntos_repaso disable row level security;

-- Diagnostico, por si algo no cuadra:
--   select relrowsecurity from pg_class where relname = 'puntos_repaso';
--   select policyname, roles, cmd from pg_policies where tablename = 'puntos_repaso';
