-- ============================================================
-- Subtemas marcados como terminados a mano
-- Ejecutar en Supabase -> SQL Editor.
--
-- El sorteo de Mi Estudio solo elige subtemas que ya pasaron el 90% de sus horas
-- de meta (ver subtemasCumplidos() en index.html). Si terminaste de estudiar algo
-- corto antes de llegar a esa marca, no habia forma de meterlo al sorteo sin
-- inflar horas a mano. Esta tabla guarda esa marca aparte: no toca el plan, las
-- metas ni las horas hechas, solo hace que el subtema entre al sorteo igual.
--
-- Sin esta tabla la app funciona igual, solo que el boton ✅ de cada subtema
-- muestra el error de "falta crear la tabla" en vez de guardar.
-- ============================================================

create table if not exists subtemas_terminados (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  tema        text not null,   -- 'Déontologie', 'Droit civil', ...
  subtema     text not null,   -- subtema del plan al que pertenece
  unique (tema, subtema)
);

create index if not exists subtemas_terminados_tema_subtema_idx
  on subtemas_terminados (tema, subtema);

-- ------------------------------------------------------------
-- Permisos (RLS)
-- La app no tiene login: todo entra con la anon key, igual que el resto de las
-- tablas del proyecto. Una tabla creada por SQL ya viene sin RLS, pero si la
-- creaste desde el Table Editor si lo tiene, y sin politicas el select devuelve []
-- en silencio y el insert falla con 42501. Esta linea la deja como las demas.
-- ------------------------------------------------------------

alter table public.subtemas_terminados disable row level security;
